-- MySQL Script generated by MySQL Workbench
-- Sun Dec  8 11:15:18 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dbEasyLife
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbEasyLife
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbEasyLife` DEFAULT CHARACTER SET utf8 ;
USE `dbEasyLife` ;

-- -----------------------------------------------------
-- Table `dbEasyLife`.`Categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbEasyLife`.`Categorias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` TEXT NOT NULL,
  `imagen` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbEasyLife`.`Subcategorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbEasyLife`.`Subcategorias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `idCategoria` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk1_subcategorias_idx` (`idCategoria` ASC),
  CONSTRAINT `fk1_subcategorias`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `dbEasyLife`.`Categorias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbEasyLife`.`Servicios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbEasyLife`.`Servicios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `idSubcategoria` INT NULL,
  `precio` DECIMAL(4,2) NOT NULL,
  `imagen` VARCHAR(255) NULL,
  `descripcion` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk1_servicios_idx` (`idSubcategoria` ASC),
  CONSTRAINT `fk1_servicios`
    FOREIGN KEY (`idSubcategoria`)
    REFERENCES `dbEasyLife`.`Subcategorias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbEasyLife`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbEasyLife`.`Usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `telefono` INT NOT NULL,
  `direccion` VARCHAR(255) NOT NULL,
  `dni` VARCHAR(9) NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `acreditacion` VARCHAR(45) NULL,
  `contrasenya` VARCHAR(255) NOT NULL,
  `imagen` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `DNI_UNIQUE` (`dni` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbEasyLife`.`Compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbEasyLife`.`Compra` (
  `idServicio` INT NOT NULL,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`idServicio`, `idUsuario`),
  INDEX `fk2_compras_idx` (`idUsuario` ASC),
  CONSTRAINT `fk1_compras`
    FOREIGN KEY (`idServicio`)
    REFERENCES `dbEasyLife`.`Servicios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk2_compras`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `dbEasyLife`.`Usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbEasyLife`.`Provee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbEasyLife`.`Provee` (
  `idServicio` INT NOT NULL,
  `idProveedor` INT NOT NULL,
  PRIMARY KEY (`idServicio`, `idProveedor`),
  INDEX `fk2_provee_idx` (`idProveedor` ASC),
  CONSTRAINT `fk1_provee`
    FOREIGN KEY (`idServicio`)
    REFERENCES `dbEasyLife`.`Servicios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk2_provee`
    FOREIGN KEY (`idProveedor`)
    REFERENCES `dbEasyLife`.`Usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbEasyLife`.`Colaboradores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbEasyLife`.`Colaboradores` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `imagen` VARCHAR(255) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbEasyLife`.`Colabora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbEasyLife`.`Colabora` (
  `idServicio` INT NOT NULL,
  `idColaborador` INT NOT NULL,
  PRIMARY KEY (`idServicio`, `idColaborador`),
  INDEX `fk2_colabora_idx` (`idColaborador` ASC),
  CONSTRAINT `fk1_colabora`
    FOREIGN KEY (`idServicio`)
    REFERENCES `dbEasyLife`.`Servicios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk2_colabora`
    FOREIGN KEY (`idColaborador`)
    REFERENCES `dbEasyLife`.`Colaboradores` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbEasyLife`.`ImagenesCarrousel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbEasyLife`.`ImagenesCarrousel` (
  `id` INT NOT NULL,
  `imagen` VARCHAR(255) NOT NULL,
  `titulo` VARCHAR(100) NULL,
  `descripcion` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;